version: "3.9"

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=8618055830
      - DB_NAME=expenses
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 8618055830
      MYSQL_DATABASE: expenses
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
