version: "3.9"

services:
  app:
    build: .
    container_name: expense-tracker-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=8618055830
      - DB_NAME=expenses
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 8618055830
      MYSQL_DATABASE: expenses
    ports:
      - "3307:3306"  # Changed to avoid local conflict
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
